# Mirror specific services
version: '3.7'

services:
  storage:
    command:
      - fix-mirror
      - storage

  content-replayer:
    image: softwareheritage/base:${SWH_IMAGE_TAG:-latest}
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: content-replayer
        target: /etc/softwareheritage/config.yml
    command:
      - content-replayer
    depends_on:
      - objstorage

configs:
  content-replayer:
    file: conf/content-replayer.yml
