# Mirror specific services
version: '3.7'

services:
  storage:
    command:
      - fix-mirror
      - storage

  graph-replayer:
    image: softwareheritage/base:${SWH_IMAGE_TAG:-latest}
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

configs:
  graph-replayer:
    file: conf/graph-replayer.yml
