# Mirror specific services
version: '3.7'

services:
  graph-replayer-content:
    image: softwareheritage/base:20200617-135429
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer-remote-content
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

  graph-replayer-revision:
    image: softwareheritage/base:20200617-135429
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer-remote-revision
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

  graph-replayer-directory:
    image: softwareheritage/base:20200617-135429
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer-remote-directory
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

  graph-replayer-origin:
    image: softwareheritage/base:20200617-135429
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer-remote-origin
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

  graph-replayer-snapshot:
    image: softwareheritage/base:20200617-135429
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer-remote-snapshot
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

  graph-replayer-release:
    image: softwareheritage/base:20200617-135429
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    configs:
      - source: graph-replayer-remote-release
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage

configs:
  graph-replayer-remote-content:
    file: conf/graph-replayer/remote/content.yml
  graph-replayer-remote-revision:
    file: conf/graph-replayer/remote/revision.yml
  graph-replayer-remote-directory:
    file: conf/graph-replayer/remote/directory.yml
  graph-replayer-remote-origin:
    file: conf/graph-replayer/remote/origin.yml
  graph-replayer-remote-release:
    file: conf/graph-replayer/remote/release.yml
  graph-replayer-remote-snapshot:
    file: conf/graph-replayer/remote/snapshot.yml
