# Mirror specific services
version: '3.7'

services:
  graph-replayer:
    image: softwareheritage/replayer:${SWH_IMAGE_TAG:-latest}
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
      STATSD_TAGS: 'role:content-replayer,hostname:${HOSTNAME}'
    configs:
      - source: graph-replayer
        target: /etc/softwareheritage/config.yml
    command:
      - graph-replayer
    depends_on:
      - storage
      - redis

configs:
  graph-replayer:
    file: conf/graph-replayer.yml
    name: graph-replayer
