# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://nginx:5081/prometheus
    access: proxy
    isDefault: true
    version: 1
    editable: false
