---
apiVersion: v1
kind: ConfigMap
metadata:
  name: objstorage
data:
  config.yml: |
    objstorage:
      cls: pathslicing
      args:
        root: "/srv/softwareheritage/objects"
        slicing: 0:1/1:5
    client_max_size: 1073741824
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: objstorage-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: objstorage-pv
  local:
    path: /srv/softwareheritage-kube/objects
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        # TODO adapt for your needs
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: objstorage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: objstorage-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objstorage
  labels:
    app: objstorage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objstorage
  template:
    metadata:
      labels:
        app: objstorage
    spec:
      containers:
      - name: objstorage
        image: registry.default/softwareheritage/base:latest
        args: 
          - objstorage
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
        - name: STATSD_HOST
          value: "prometheus-statsd-exporter"
        - name: STATSD_PORT
          value: "9125"
        volumeMounts:
        - mountPath: "/srv/softwareheritage/objects"
          name: objstorage-pvc
        - name: config
          mountPath: /etc/softwareheritage/config.yml
          subPath: config.yml
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: objstorage
        - name: objstorage-pvc
          persistentVolumeClaim:
            claimName: objstorage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: objstorage
spec:
  type: ClusterIP
  selector:
    app: objstorage
  ports:
    - port: 5003
      targetPort: 5003
